### ISSUE TITLE
Java Compatibility lower to 1.5

### ISSUE THREAD

**Issue by andyrozman** [nerro/table-layout#16]
Could you please change requirement in maven to Java 1.5? I have just made a "fork" of original project bacuse I need new maven release with java 1.5... 

And after that I found this project...  I could drop my project if you would lower requirement to java 1.5 (at the time it doesn't require higher than that)...

**Comment by nerro** [comment]
@andyrozman, I'll check your issue at the weekend. My idea was: perhaps leave compatibility for versions `4.2.*` and do something new in version `5.*`. So I can break compatibility according semantic version guidelines.

**Comment by nerro** [comment]
@me, currently `source` and `target` levels aren't seen in Travis-CI logs. Config file should be changed, so I can track the java compatibility for whole build matrix.

**Comment by andyrozman** [comment]
I am not sure if Travis supports Java 1.5.

**Comment by nerro** [comment]
We don't need to compile with Java 1.5 (http://docs.oracle.com/javase/7/docs/technotes/tools/windows/javac.html#crosscomp-example).

**Comment by andyrozman** [comment]
I am sorry to say that this target and source version don't work that good. Which is reason why for most compilation we use real JDK 1.5... It might work for this project though, because it's very simple... You just need to be careful, that you don't use any syntax that is invalid in java 1.5 (for example you can't use @Override on methods you implement (if you implement interface, you can't use it on thoose methods)).
I am not sure what maven will do when he encounters this. You might need to use additional flags in definition.

**Comment by nerro** [comment]
@andyrozman, can you try the new version `4.3.0` and tell me, if you have some issue with the new version?

**Comment by andyrozman** [comment]
It seems to work OK... Thanks...
