### ISSUE TITLE
add all other files from original project

### ISSUE THREAD

**Issue by andyrozman** [nerro/table-layout#19]
Add all other files from original project:
- builders
- extensions
- all example classes (put them under test/java/)
- original web page with all articles

**Comment by nerro** [comment]
All these file can be found under https://github.com/nerro/table-layout-examples. Please check [README.md](https://github.com/nerro/table-layout/blob/master/README.md).

PRs are welcome :smile:.

**Comment by andyrozman** [comment]
builders and extensions should be in main projects, since those two are not examples...

**Comment by nerro** [comment]
With [ComponentArranger](https://github.com/nerro/table-layout-examples/blob/master/builders/info/clearthought/layout/ComponentArranger.java) you're right, it should be moved from example project.
But extensions are not part of table-layout core project, see (https://github.com/nerro/table-layout-examples/blob/master/extensions/info/clearthought/layout/TableLayoutPersistenceDelegate.java#L141).

Do you make a PR for this?
