### ISSUE TITLE
Licensing info?

### ISSUE THREAD

**Issue by apjanke** [nerro/table-layout#22]
Any idea what license this library is distributed under? I'd like to use it in my own project (https://github.com/apjanke/matlab-jump) but would like to get a better idea of what the licensing situation is before redistributing it.

**Comment by nerro** [comment]
👋 @apjanke,
The LICENSE file is under resource folder (https://github.com/nerro/table-layout/blob/master/subprojects/layout/src/main/resources/META-INF/LICENCE). This is original license from Daniel.

P.S.: thanks for pointing me about license, I'll move the file into root of the project, so license info will be shown and parse automatically by GitHub. The project is pretty old :), so GitHub didn't support license info at that time.

**Comment by apjanke** [comment]
Ah, thank you!

Closing this since my question is answered.
